modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "soulstriders"
version = "${file.jarVersion}"
displayName = "Soul Striders"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://soulstriders.teamhollow.net"
issueTrackerURL = "https://github.com/teamhollow/soulstriders/issues"
logoFile = "pack.png"
credits = "Made possible by people™"
authors = "Team Hollow"
description = '''
Striders that stride over souls
'''

[[dependencies.soulstriders]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.soulstriders]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
